export const FETCH_TICKETS_START = 'FETCH_TICKETS_START'
export const FETCH_TICKETS_ERROR = 'FETCH_TICKETS_ERROR'
export const FETCH_TICKETS_SUCCESS = 'FETCH_TICKETS_SUCCESS'

export const FETCH_COURSE_START = 'FETCH_COURSE_START'
export const FETCH_COURSE_ERROR = 'FETCH_COURSE_ERROR'
export const FETCH_COURSE_SUCCESS = 'FETCH_COURSE_SUCCESS'
export const SET_CHECKBOX_VALUE = 'SET_CHECKBOX_VALUE'


export const SELECT_VALUTE = 'SELECT_VALUTE'
export const ALL = "ALL"
export const FILTER_TRANSFERS = "FILTER_TRANSFERS"


export const OPEN_MODAL_FORM = 'OPEN_MODAL_FORM'
export const CLOSE_MODAL_FORM = 'CLOSE_MODAL_FORM'
export const OPEN_MODAL_SUCCESS = 'OPEN_MODAL_SUCCESS'
export const CLOSE_MODAL_SUCCESS = 'CLOSE_MODAL_SUCCESS'



